version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db:27017/tink-link
  db:
    image: mongo:latest