version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: mongodb://db:27017/tink-link
    networks:
      - local-network
  db:
    image: mongo:latest
    networks:
      - local-network
networks:
  local-network: