module.exports = {
  parser: "@typescript-eslint/parser",
  extends: [
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended",
    "plugin:react/recommended",
    "plugin:unicorn/recommended",
    "prettier/unicorn",
    "plugin:@typescript-eslint/recommended",
  ],
  parserOptions: {
    ecmaVersion: "2018",
    sourceType: "module",
    ecmaFeatures: {
      jsx: true,
    },
  },
  env: {
    es6: true,
    node: true,
    browser: true,
  },
  plugins: ["@typescript-eslint", "prettier", "react", "unicorn", "simple-import-sort"],
  settings: {
    react: {
      version: "detect",
    },
  },
  rules: {
    "prefer-spread": "error",
    "prefer-object-spread": "error",
    "no-param-reassign": "error",
    "prefer-template": "error",
    "object-shorthand": ["error", "always"],
    "no-nested-ternary": "error",
    "no-negated-condition": "error",
    "prefer-destructuring": [
      "error",
      {
        array: false,
        object: true,
      },
      {
        enforceForRenamedProperties: false,
      },
    ],
    "prettier/prettier": [
      "error",
      {
        proseWrap: "never",
        trailingComma: "all",
        arrowParens: "avoid",
        indent: "2",
      },
    ],
    "comma-dangle": 0,
    "react/prop-types": 0,
    "@typescript-eslint/camelcase": 0,
    "@typescript-eslint/explicit-member-accessibility": 0,
    "@typescript-eslint/interface-name-prefix": 0,
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/no-empty-interface": 0,
    "@typescript-eslint/no-parameter-properties": ["error", { allows: ["public"] }],
    "keyword-spacing": [
      "error",
      {
        overrides: {
          function: { after: false },
          async: { after: false },
        },
      },
    ],
    "space-before-function-paren": [
      "error",
      { anonymous: "never", named: "never", asyncArrow: "always" },
    ],
    "space-before-function-paren": 0,
    "unicorn/filename-case": 0,
    "unicorn/prevent-abbreviations": 0,
    "unicorn/no-null": 0,
    "unicorn/no-useless-undefined": 0,
    "unicorn/prefer-set-has": 0,
    "unicorn/no-reduce": 0,
    "unicorn/prefer-node-remove": 0,
    "unicorn/prefer-number-properties": 0,
    "unicorn/no-fn-reference-in-iterator": 0,
    "padding-line-between-statements": [
      "error",
      {
        blankLine: "always",
        prev: "import",
        next: ["block-like", "const", "let", "export", "class"],
      },
      { blankLine: "always", prev: ["let", "const"], next: "*" },
      { blankLine: "any", prev: ["let", "const"], next: ["let", "const"] },
      { blankLine: "always", prev: "block-like", next: "return" },
    ],
    "simple-import-sort/exports": "error",
    "simple-import-sort/imports": [
      "error",
      {
        groups: [
          ["^@?\\w.*\\u0000$", "^[^.].*\\u0000$", "^\\..*\\u0000$"],
          ["^\\u0000"],
          ["^"],
          ["^@\\w"],
          ["^#\\w"],
          ["^\\."],
        ],
      },
    ],
    "no-use-before-define": "off",
    "no-unused-vars": "off",
    "no-unexpected-multiline": "error",
    "@typescript-eslint/no-unused-vars": ["error", { ignoreRestSiblings: true }],
    "@typescript-eslint/no-use-before-define": "off",
    "no-setter-return": 0,
    "no-import-assign": 0,
    "no-dupe-else-if": 0,
    "accessor-pairs": 0,
    "array-callback-return": 0,
    "computed-property-spacing": 0,
    "func-names": 0,
    "no-extra-parens": 0,
    "no-dupe-class-members": 0,
    "no-magic-number": 0,
    radix: 0,
    "use-isnan": 0,
    yoda: 0,
    "no-async-promise-executor": "off",
    "no-misleading-character-class": "off",
    "no-prototype-builtins": "off",
    "no-shadow-restricted-names": "off",
    "no-useless-catch": "off",
    "no-with": "off",
    "require-atomic-updates": "off",

    "no-console": ["error", { allow: ["warn", "error", "info"] }],
  },
};
