export const scopeData = [
  // "account-verification-reports:read",
  // "account-verification-reports:write",
  "accounts:read",
  "authorization:grant",
  "balances:read",
  // "credentials:read",
  // "identity:read",
  // "link-session:read",
  // "link-session:write",
  // "payment:read",
  // "payment:write",
  // "provider-consents:read",
  // "providers:read",
  "transactions:read",
  // "transfer:execute",
  // "transfer:read",
  "user:read",
  // "user:web_hooks"
].join(",");
